# Generated by Django 2.2.19 on 2022-08-12 04:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.TextField(
                default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
